name: CI

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: 'Create new release'
        required: true
        type: boolean
  push:
    branches:
      - master
      - ci
    paths: ['.github/workflows/**', '**/CMakeLists.txt', '**/Makefile', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp', '**/*.cu']
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['**/CMakeLists.txt', '**/Makefile', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp', '**/*.cu']

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  

jobs:
  ubuntu-latest-cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release

      - name: Get commit hash
        id: commit
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        uses: pr-mpt/actions-commit-hash@v2

      - name: Fetch system info
        id: system-info
        run: |
          echo "CPU_ARCH=`uname -m`" >> "$GITHUB_OUTPUT"
          echo "OS_NAME=`lsb_release -s -i`" >> "$GITHUB_OUTPUT"
          echo "OS_VERSION=`lsb_release -s -r`" >> "$GITHUB_OUTPUT"
          echo "OS_TYPE=`uname -s`" >> "$GITHUB_OUTPUT"

      - name: Pack artifacts
        id: pack_artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        run: |
          cp ggml/LICENSE ./build/bin/ggml.txt
          cp LICENSE ./build/bin/stable-diffusion.cpp.txt
          zip -j sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip ./build/bin/*

      - name: Upload artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip


  macOS-latest-cmake:
    runs-on: macos-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Dependencies
        id: depends
        run: |
          brew install zip

      - name: Build
        id: cmake_build
        run: |
          sysctl -a
          mkdir build
          cd build
          cmake .. -DGGML_AVX2=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release

      - name: Get commit hash
        id: commit
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        uses: pr-mpt/actions-commit-hash@v2

      - name: Fetch system info
        id: system-info
        run: |
          echo "CPU_ARCH=`uname -m`" >> "$GITHUB_OUTPUT"
          echo "OS_NAME=`sw_vers -productName`" >> "$GITHUB_OUTPUT"
          echo "OS_VERSION=`sw_vers -productVersion`" >> "$GITHUB_OUTPUT"
          echo "OS_TYPE=`uname -s`" >> "$GITHUB_OUTPUT"

      - name: Pack artifacts
        id: pack_artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        run: |
          cp ggml/LICENSE ./build/bin/ggml.txt
          cp LICENSE ./build/bin/stable-diffusion.cpp.txt
          zip -j sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip ./build/bin/*

      - name: Upload artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip


  windows-latest-cmake:
    runs-on: windows-latest
    # https://github.com/leejet/stable-diffusion.cpp/issues/52 ggml error when using "--schedule kerras" with clblast #52
    # Thank you very much superkuh https://github.com/leejet/stable-diffusion.cpp/issues/48#issuecomment-1869239181
    # stable-diffusion.cpp has not add the support for OpenCL
    
    strategy:
      matrix:
        include:
          - build: 'noavx'
            defines: '-DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF -DSD_BUILD_SHARED_LIBS=ON'
          - build: 'noavx-opencl-clblast-and-openblas'
            defines: '-DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF -DSD_BUILD_SHARED_LIBS=ON -DGGML_OPENBLAS=ON -DGGML_CLBLAST=ON -DCLBLAST_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\include -DCLBLAST_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\lib\clblast.lib -DOPENCL_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\include -DOPENCL_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\lib\OpenCL.lib -DOPENBLAS_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\include -DOPENBLAS_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\lib\libopenblas.lib'
          - build: 'noavx-sse3-opencl-clblast-and-openblas'
            defines: '-DGGML_SSE3=ON -DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF -DSD_BUILD_SHARED_LIBS=ON -DGGML_OPENBLAS=ON -DGGML_CLBLAST=ON -DCLBLAST_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\include -DCLBLAST_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\lib\clblast.lib -DOPENCL_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\include -DOPENCL_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\lib\OpenCL.lib -DOPENBLAS_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\include -DOPENBLAS_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\lib\libopenblas.lib'
          - build: 'noavx-sse3-opencl-and-clblast'
            defines: ' -DGGML_SSE3=ON -DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF -DSD_BUILD_SHARED_LIBS=ON -DGGML_CLBLAST=ON -DCLBLAST_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\include -DCLBLAST_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\lib\clblast.lib -DOPENCL_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\include -DOPENCL_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\lib\OpenCL.lib'

          #- build: 'avx2-opencl-clblast'
          #  defines: '-DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON -DGGML_CLBLAST=ON -DCLBLAST_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\include -DCLBLAST_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\lib\clblast.lib -DOPENCL_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\include -DOPENCL_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\lib\OpenCL.lib -DOPENBLAS_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\include -DOPENBLAS_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\lib\libopenblas.lib'
          #- build: 'avx-opencl-clblast'
            #defines: '-DGGML_AVX2=OFF -DSD_BUILD_SHARED_LIBS=ON -DGGML_CLBLAST=ON -DCLBLAST_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\include -DCLBLAST_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\clblast\lib\clblast.lib -DOPENCL_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\include -DOPENCL_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\OpenCL\lib\OpenCL.lib -DOPENBLAS_INC=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\include -DOPENBLAS_LIB=D:\a\stable-diffusion.cpp\stable-diffusion.cpp\openBlas\lib\libopenblas.lib'
          #- build: 'avx'
            #defines: '-DGGML_AVX2=OFF -DSD_BUILD_SHARED_LIBS=ON -DGGML_CLBLAST=ON'
          #- build: 'avx512'
            #defines: '-DGGML_AVX512=ON -DSD_BUILD_SHARED_LIBS=ON'
          #- build: 'avx2' 
            #defines: '-DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON'
          #- build: 'cuda12'
            #defines: '-DSD_CUBLAS=ON -DSD_BUILD_SHARED_LIBS=ON'
          #- build: 'rocm5.5'
            #defines: '-G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DSD_HIPBLAS=ON -DCMAKE_BUILD_TYPE=Release -DAMDGPU_TARGETS="gfx1100;gfx1102;gfx1030" -DSD_BUILD_SHARED_LIBS=ON'
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive    
      - name: Download and unzip OpenCL-SDK
        id: download-and-unzip-opencl

        if: ${{ contains(matrix.build , 'opencl') }}
        run: Start-BitsTransfer -Source "https://github.com/KhronosGroup/OpenCL-SDK/releases/download/v2023.12.14/OpenCL-SDK-v2023.12.14-Win-x64.zip" -Destination "OpenCL.zip";7z x ".\OpenCL.zip" -o".\";Copy-Item ./OpenCL-SDK-v2023.12.14-Win-x64/  openCL -recurse -force 
      - name: Download and unzip clBLAST
        if: ${{ contains(matrix.build , 'clblast') }}
        id: download-and-unzip-clblast
        run: Start-BitsTransfer -Source "https://github.com/CNugteren/CLBlast/releases/download/1.6.2/CLBlast-1.6.2-windows-x64.zip" -Destination "clBLAST.zip";7z x ".\clBLAST.zip" -o".\";7z x ".\CLBlast-1.6.2-windows-x64.7z" -o".\";Copy-Item ./CLBlast-1.6.2-windows-x64/ clblast -recurse -force
      - name: Download and unzip openblas
        id: download-opencl-clblast-and-openblas
        if: ${{ contains(matrix.build , 'openblas') }}
        run: Start-BitsTransfer -Source "https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.27/OpenBLAS-0.3.27-x64.zip" -Destination "openBlas.zip";mkdir openBlas;7z x ".\openBlas.zip" -o".\openBlas"
        
         
      - name: Install cuda-toolkit
        id: cuda-toolkit
        if: ${{ matrix.build == 'cuda12' }}
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.2.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'

      - name: Install rocm-toolkit
        id: rocm-toolkit
        if: ${{ matrix.build == 'rocm5.5' }}
        uses: Cyberhan123/rocm-toolkit@v0.1.0
        with:
          rocm: '5.5.0'

      - name: Install Ninja
        id: install-ninja
        if: ${{ matrix.build == 'rocm5.5' }}
        uses: urkle/action-get-ninja@v1
        with:
          version: 1.11.1

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.defines }}
          cmake --build . --config Release

      - name: Check AVX512F support
        id: check_avx512f
        if: ${{ contains(matrix.build,'avx512') }}
        continue-on-error: true
        run: |
          cd build
          $vcdir = $(vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
          $msvc = $(join-path $vcdir $('VC\Tools\MSVC\'+$(gc -raw $(join-path $vcdir 'VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt')).Trim()))
          $cl =  $(join-path $msvc 'bin\Hostx64\x64\cl.exe')
          echo 'int main(void){unsigned int a[4];__cpuid(a,7);return !(a[1]&65536);}' >> avx512f.c
          & $cl /O2 /GS- /kernel avx512f.c /link /nodefaultlib /entry:main
          .\avx512f.exe && echo "AVX512F: YES" && ( echo HAS_AVX512F=1 >> $env:GITHUB_ENV ) || echo "AVX512F: NO"

      - name: Check SSE3 support
        id: check_sse3
        if: ${{ contains(matrix.build,'sse3') }}
        continue-on-error: true
        run: |
          cd build
          $vcdir = $(vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
          $msvc = $(join-path $vcdir $('VC\Tools\MSVC\'+$(gc -raw $(join-path $vcdir 'VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt')).Trim()))
          $cl =  $(join-path $msvc 'bin\Hostx64\x64\cl.exe')
          echo 'int main(void){unsigned int a[4];__cpuid(a,1);return a[2]&(1 << 0);}' >> tmmintrin.c
          & $cl /O2 /GS- /kernel tmmintrin.c /link /nodefaultlib /entry:main
          .\tmmintrin.exe && echo "SSE3: YES" && ( echo HAS_SSE3=1 >> $env:GITHUB_ENV ) || echo "SSE3: NO"

        
      - name: Get commit hash
        id: commit
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        uses: pr-mpt/actions-commit-hash@v2

      - name: Pack artifacts
        id: pack_artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || (github.event.inputs.create_release == 'true') }}
        run: |
          $filePath = ".\build\bin\Release\*"
          if (Test-Path $filePath) {
            echo "Exists at path $filePath"
            Copy-Item ggml/LICENSE .\build\bin\Release\ggml.txt
            Copy-Item LICENSE .\build\bin\Release\stable-diffusion.cpp.txt
          } elseif (Test-Path ".\build\bin\stable-diffusion.dll") {
          $filePath = ".\build\bin\*"
            echo "Exists at path $filePath"
            Copy-Item ggml/LICENSE .\build\bin\ggml.txt
            Copy-Item LICENSE .\build\bin\stable-diffusion.cpp.txt
          } else {
            ls .\build\bin
            throw "Can't find stable-diffusion.dll"
          }
          if (Test-Path ".\openBlas") {
            echo "Exists at path .\openBlas."
            Copy-Item openBlas\bin\libopenblas.dll .\build\bin\Release\libopenblas.dll}
          if (Test-Path ".\clBLAST") { 
            Copy-Item clBLAST\bin\ .\build\bin\Release\ -recurse -force}
          7z a sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-win-${{ matrix.build }}-x64.zip $filePath

      - name: Copy and pack Cuda runtime
        id: pack_cuda_runtime
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.build == 'cuda12' ) || ( github.event.inputs.create_release == 'true' && matrix.build == 'cuda12' ) }}
        run: |
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          $dst='.\build\bin\cudart\'
          robocopy "${{steps.cuda-toolkit.outputs.CUDA_PATH}}\bin" $dst cudart64_*.dll cublas64_*.dll cublasLt64_*.dll
          7z a cudart-sd-bin-win-cu12-x64.zip $dst\*

      - name: Upload Cuda runtime
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.build == 'cuda12' ) || (github.event.inputs.create_release == 'true'  && matrix.build == 'cuda12' ) }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            cudart-sd-bin-win-cu12-x64.zip

      - name: Upload artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-win-${{ matrix.build }}-x64.zip

  release:
    if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}

    runs-on: ubuntu-latest

    needs:
      - ubuntu-latest-cmake
      - macOS-latest-cmake
      - windows-latest-cmake

    steps:
      - name: Download artifacts
        id: download-artifact
        uses: actions/download-artifact@v3

      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Create release
        id: create_release
        uses: anzz1/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}

      - name: Upload release
        id: upload_release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path');
            const fs = require('fs');
            const release_id = '${{ steps.create_release.outputs.id }}';
            for (let file of await fs.readdirSync('./artifact')) {
              if (path.extname(file) === '.zip') {
                console.log('uploadReleaseAsset', file);
                await github.repos.uploadReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release_id,
                  name: file,
                  data: await fs.readFileSync(`./artifact/${file}`)
                });
              }
            }
